### PR TITLE
Fix/277/check why the applicants form isn't showing

### PR DESCRIPTION
**Pull request by AxelUZ**
# What does this PR do?
Fix the error that if you exit without answering the applicationForm, then it lets you enter "IntershipProjects" with the interface as if you had filled the applicationForm.

https://github.com/wizeline/remix-project-lab/assets/58340818/9e18d92d-6078-4ef4-8afa-c3c7789e3883

# Where should the reviewer start?
app/core/layouts/Header.tsx
app/routes/internshipProjects/$projectId/index.tsx
app/routes/internshipProjects/index.tsx

# How should this be manually tested?
1. Login via linkdin
2. Exit the applicationForm without answering
3. Enter to View Projects
4. Verify that the home button appears in the header instead of your linkdin email address.
5. Verify that when you enter a project the button to answer the form appears instead of the apply button.

https://github.com/wizeline/remix-project-lab/assets/58340818/af146a90-de05-43d6-a8f3-8a64ce84e2ca

# Any background context you want to provide?

# What are the relevant tickets?
#277 

# Screenshots
Captura de pantalla 2023-11-22 a la(s) 5 33 03 p m

# Questions

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

### CODE REVIEW

**Comment by beatriz-sanchez-wizeline** [comment]
Thanks for providing the screen recordings @AxelUZ, makes it much easier to understand.

I am wondering if filling the form from a specific project might make an intern think that he or she has already applied, which could be problematic. He or she might not know that the application didn't go through and think it did because he filled the application form. 

For the intern's application flow, I think there are two possible scenarios:

**Scenario 1:**
We do not allow applicant users to navigate to the projects until they have filled the form. Like we do when they register, this means redirecting users to the application form whenever they try to go to the projects view or a specific project. Effectively forcing them to fill the application before interacting with projects.

**Scenario 2:**
We want to allow users to explore projects before filling the application.
In this case I think that:
1. We shouldn't force new users to fill the application as soon as they register, because they have not seen if there is a project they are interested in. **Newly registered users should instead be redirected to the projects view<**.
2. Users could **hit the "Apply"** button on a project and **if they haven't filled in the form, they are simply redirected to it.** In this case, I would suggest that **once they fill the form, they do not need to hit the "Apply" button again**, we should know they wanted to apply to that particular project.

I believe Scenario 2 makes more sense which is similar to what you propose. If you agree, do you think you could add this behaviour? What are your thoughts?

**Comment by AxelUZ** [comment]
In this new commit please verify that when pressing the "Home" buttons located in "/IntershipProjects" make a Logout. Verify that the "View Projects" button when there is no active user, sends you to "/IntershipProjects" so you can see the projects before applying.

**Comment by AxelUZ** [comment]
"Home" buttons located in "/IntershipProjects" make a Logout.

https://github.com/wizeline/remix-project-lab/assets/58340818/0693d959-3d6f-447b-8d71-fe01e543ad61

Verify that the "View Projects" button when there is no active user, sends you to "/IntershipProjects" so you can see the projects before applying.

https://github.com/wizeline/remix-project-lab/assets/58340818/7f582159-726d-4497-be9f-9b3a0b2e6156

**Review by beatriz-sanchez-wizeline — APPROVED** [review]
Looks good to me! 
> Verify that the home button appears in the header instead of your linkedin email address.
✔️ 
> Verify that when you enter a project the button to answer the form appears instead of the apply button.
✔️ 
> Verify that when pressing the "Home" buttons located in "/InternshipProjects" make a Logout. 
✔️ 
> Verify that the "View Projects" button when there is no active user, sends you to "/InternshipProjects" so you can see the projects before applying.
✔️

**Pull request merged**
