### PR TITLE
Feat/104/implement precommit scripts

### PR DESCRIPTION
**Pull request by JCoronaWize**
# What does this PR do?
Adds pre-commit scripts to prevent errors for ESLINt and Typescript

# Where should the reviewer start?
Check the new .husky folder

# How should this be manually tested?
run repo locally.
run npm install
Try applying a change and commit it. (git commit -m "Some change to a file")
If an ESLINT or Typescript error is found the changes will not be commited

# Any background context you want to provide?

# What are the relevant tickets?
#104 

# Screenshots

# Questions

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

### CODE REVIEW

**Comment by martinrobled0** [comment]
when I do a git add I got this message, that is ok?
image

**Comment by JCoronaWize** [comment]
That message is expected to appear when commit is run without files been staged

**Comment by jackbravo** [comment]
Sorry @JCoronaWize 🙈  I'm not 100% sure about this. It mainly adds husky as a dependency, for something that github actions is now also doing. I just enabled disallowing merging something when the PR status checks fail. So both things do more or less the same.

image

What does the team think? Should we add this dependency, and have this running locally before every push? @juanan0309 , @LuisTejedaS , @martinrobled0 . Also what do you think @JCoronaWize ?

**Comment by JCoronaWize** [comment]
During today's meet we talked about this, and agreed to make this to work before pushing the repo in order to detect and correct typescript errors earlier.
I'll update this to work on pre-push

**Comment by JCoronaWize** [comment]
Added a pre-push script which prevents upload if there are TS or ESLint errors.
pre-commit only validates TS (As mentioned during the meeting, to prevent ESlint blockers (e.g. console.log) for local development)
Modified some files because a rule for console.log was added (.warning and .error are still valid)

**Comment by martinrobled0** [comment]
Can you resolve the ESLint errors? ... and regarding those, should this script recognize those errors? 🤔

**Comment by JCoronaWize** [comment]
@martinrobled0 yes it detects and indicates de errors... or did I misunderstood the question 😅 ?

**Comment by martinrobled0** [comment]
@JCoronaWize sorry I mean, these errors didn't appear in the pre push?

**Comment by JCoronaWize** [comment]
@martinrobled0 The console.log ESLint errors? Yes, they appeared and prevented the push (👍 ), after correcting them I was able to make this latest push.
I commented the lines in files (//console.log()) in case we wished to turn them into .error or .warn.

**Review by LuisTejedaS — APPROVED** [review]

**Pull request merged**
