### PR TITLE
Packages update - Prisma 3.14 to 4.3.1

### PR DESCRIPTION
**Pull request by Andresmagic**
# What does this PR do?

Update on the packages of the project, the more important one is prisma 3.14 - 4.3.1

# Where should the reviewer start?

Check the changes in the `schema.prisma` and review what is needed for this new version to work 

# How should this be manually tested?

# Any background context you want to provide?

# What are the relevant tickets?

# Screenshots

# Questions

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

### CODE REVIEW

**Comment by Andresmagic** [comment]
Here is the code we used to deal with the BigInt problem in the pass meeting:
`return new Response(JSON.stringify({ data }, (key, value) =>
 typeof value === 'bigint'
    ? value.toString()
    : value // return everything else unchanged
), {
  headers: {
    "Content-Type": "application/json; charset=utf-8",
  },
});
`

**Comment by Andresmagic** [comment]
Currently working on this error: 
`TypeError: Cannot read properties of undefined (reading 'length')
    at Projects (D:\remix-project-lab\app\routes\projects\index.tsx:208:31)
    at processChild (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at renderToString (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at handleRequest (D:\remix-project-lab\app\entry.server.tsx:11:18)
    at handleDocumentRequest (D:\remix-project-lab\node_modules\@remix-run\server-runtime\server.js:400:18)
    at requestHandler (D:\remix-project-lab\node_modules\@remix-run\server-runtime\server.js:49:18)
    at D:\remix-project-lab\node_modules\@remix-run\express\server.js:39:22`

**Comment by Andresmagic** [comment]
Just added the onDelete and onUpdate that was on the previous prisma schema

**Comment by Andresmagic** [comment]
> Currently working on this error: `TypeError: Cannot read properties of undefined (reading 'length') at Projects (D:\remix-project-lab\app\routes\projects\index.tsx:208:31) at processChild (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14) at resolve (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5) at ReactDOMServerRenderer.render (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22) at ReactDOMServerRenderer.read (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29) at renderToString (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27) at handleRequest (D:\remix-project-lab\app\entry.server.tsx:11:18) at handleDocumentRequest (D:\remix-project-lab\node_modules\@remix-run\server-runtime\server.js:400:18) at requestHandler (D:\remix-project-lab\node_modules\@remix-run\server-runtime\server.js:49:18) at D:\remix-project-lab\node_modules\@remix-run\express\server.js:39:22`

 `statusFacets` is getting undefined, 'cause `data is undefined`, still looking for the cause of that

**Comment by Andresmagic** [comment]
> return new Response(JSON.stringify({ data }, (key, value) => typeof value === 'bigint' ? value.toString() : value // return everything else unchanged ), { headers: { "Content-Type": "application/json; charset=utf-8", }, });


> > Currently working on this error: `TypeError: Cannot read properties of undefined (reading 'length') at Projects (D:\remix-project-lab\app\routes\projects\index.tsx:208:31) at processChild (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14) at resolve (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5) at ReactDOMServerRenderer.render (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22) at ReactDOMServerRenderer.read (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29) at renderToString (D:\remix-project-lab\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27) at handleRequest (D:\remix-project-lab\app\entry.server.tsx:11:18) at handleDocumentRequest (D:\remix-project-lab\node_modules\@remix-run\server-runtime\server.js:400:18) at requestHandler (D:\remix-project-lab\node_modules\@remix-run\server-runtime\server.js:49:18) at D:\remix-project-lab\node_modules\@remix-run\express\server.js:39:22`
> 
> `statusFacets` is getting undefined, 'cause `data is undefined`, still looking for the cause of that

So... just did an `npm update remix` and the error get fixed. The bigInt finally appeared and it get solved with our first solution. Now all should work properly;)

**Review by jackbravo — APPROVED** [review]
I think this is a good first approach. I still think that long term it would be better to integrate https://github.com/kiliman/remix-typedjson. But I don't want to hold upgrading to v4.

**Pull request merged**
