### PR TITLE
build/170/update packages with vulnerabilities

### PR DESCRIPTION
**Pull request by martinrobled0**
# What does this PR do?
UIpdate packages with vulnerabilities

# Where should the reviewer start?
Since dependabot found some vulnerabilities [here](https://github.com/wizeline/remix-project-lab/security/dependabot) 

# How should this be manually tested?

Check the package.json

# Any background context you want to provide?

https://github.com/wizeline/remix-project-lab/security/dependabot

Also this change will affect the current test we have

# What are the relevant tickets?
#170 

# Screenshots

# Questions

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

### CODE REVIEW

**Comment by jackbravo** [comment]
hahahaha, but why do we need to comment our tests? Is it mainly the cypress tests, right? But they were supposed to be working, no? @LuisTejedaS

**Comment by juanan150** [comment]
> hahahaha, but why do we need to comment our tests? Is it mainly the cypress tests, right? But they were supposed to be working, no? @LuisTejedaS

Hi @jackbravo, welcome back!

The tests are currently broken due to the last change done in the managers section haha. It was a huge change, so @martinrobled0 finished those changes and I am currently working on updating the tests to fit the current components

**Comment by LuisTejedaS** [comment]
So i guess we are fine @juanan150 lets fix them as soon as we can

**Review by juanan150 — APPROVED** [review]
LGTM

**Comment by martinrobled0** [comment]
So, Can I merge this? @LuisTejedaS @juanan150

**Review by JCoronaWize — APPROVED** [review]
LGTM

**Pull request merged**
