### PR TITLE
Feat/212/enable linkedin in login for all users

### PR DESCRIPTION
**Pull request by AxelUZ**
# What does this PR do?
Create a profile for users logging in with linkedin and assign them the applicant role to handle redirects. It also verifies that the applicant form is answered once per account.

# Where should the reviewer start?
/app/auth.server.ts
app/routes/login.tsx

# How should this be manually tested?
1. In the "/login" log in with the option "Continue with linkedin"
2. You will be assigned the applicant's role in the "user" table and because you have not answered the applicant form you will be redirected to "/applicationForm"
3. Fill out the applicant's form and you will be redirected to "/projects"
4. logout and repeat step one, now you should be redirected to "/projects" because you have already answered the form.

IMPORTANT: This flow is for testing purposes, the redirections to "/projects" will be changed to "intershipProjects". The change will be made by @CarlosMilano  once the changes are approved.

# Any background context you want to provide?

# What are the relevant tickets?
#212 

# Screenshots
Creation of profile: 
Captura de pantalla 2023-09-15 a la(s) 2 06 52 p m

Creation of User and assign of role "applicant":
Captura de pantalla 2023-09-15 a la(s) 2 07 08 p m

Applicant creation with linkedin login email address:
Captura de pantalla 2023-09-15 a la(s) 2 07 27 p m

View when logging in with linkedin(For the moment it is for testing purposes it will be changed to "/intershipProjects" ): 
Captura de pantalla 2023-09-15 a la(s) 2 08 30 p m

# Questions

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

### CODE REVIEW

**Review by CarlosMilano — COMMENTED** [review]
It seems to be good and it work properly

**Review by maubarraganwize — APPROVED** [review]
LGTM

**Comment by martinrobled0** [comment]
I have a doubt here @jackbravo , Can applicants create new proposals?

**Comment by AxelUZ** [comment]
> I have a doubt here @jackbravo , Can applicants create new proposals?

About the new proposal, @CarlosMilano  has a branch where he has the logic for the changes in the /projects page that now would be /intershipProjects and disables the new proposal and other options.

**Pull request merged**
