### PR TITLE
Feat/259/get list of releases

### PR DESCRIPTION
**Pull request by martinrobled0**
# What does this PR do?
Add the list of realease of each project in the git hub page

# Where should the reviewer start?
the get-proyectActivity file

# How should this be manually tested?

- Select a project
- Go to the GitHub Statistics section
- Check the list of realeases (the project must have the url of the repo)

# Any background context you want to provide?

# What are the relevant tickets?
#259 

# Screenshots

image
image

# Questions
Should add a link the release page?

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

### CODE REVIEW

**Review by beatriz-sanchez-wizeline — APPROVED** [review]
Looks good to me! The script to populate the release info is working and the UI looks good. Regarding your comment on whether to add the release link, I think it is not a bad idea to add something like a badge that says "go to release" or something similar in the collapsible header or inside the collapsible. My only comment (up for discussion) is that in cases where the project may be associated with multiple GitHub repos, there is no way to filter the info (releases and project participation) by repo. I guess we can raise a new ticket to add this functionality.

**Review by AxelUZ — COMMENTED** [review]
It works very well for me . About the question if we should add a link to the release, I think it is a good option so we can review more in depth the tickets involved in that release or edit that release directly, I think we should add it.

**Comment by martinrobled0** [comment]
ok, I'll work on that link

**Comment by beatriz-sanchez-wizeline** [comment]
@martinrobled0 the button looks good, but for some reason clicking does nothing:

https://github.com/wizeline/remix-project-lab/assets/149706555/d7f196be-720b-4d03-b7ce-a289e421cf18

Having a look at the network tab on the developer tools, nothing happens when I click. Is anyone else having this issue?

**Comment by AxelUZ** [comment]
> @martinrobled0 the button looks good, but for some reason clicking does nothing:
> 
>  Screen.Recording.2023-11-22.at.14.36.30.mov 
> Having a look at the network tab on the developer tools, nothing happens when I click. Is anyone else having this issue?

I have the same problem

**Comment by beatriz-sanchez-wizeline** [comment]
> @martinrobled0 the button looks good, but for some reason clicking does nothing:

@martinrobled0 it was my bad, I forgot to re-run `npm run dev` after updating the db. It is working fine. I'll leave the PR approved.

For other reviewers, to test this branch do:
```
npx prisma migrate reset
npx prisma migrate deploy
npx prisma generate
// make sure to update your project with the repo link before running:
npx ts-node --project ./ts-node.tsconfig.json ./tasks/GitHubDataManage/getGitHubActivityByProject.ts
npm run dev # Always re-run after a DB update
```

**Pull request merged**
